### ISSUE TITLE
Problema al editar campos multiselect

### ISSUE THREAD

**Issue by dev-cadira** [dev-cadira/cadira#1]
Bug: in the Calendar (Activities) module the Multi-Select Combo Box type field does not work.

![2021-08-28 19_21_43-Clipboard](https://user-images.githubusercontent.com/89658833/131225927-ad39339b-85e7-40be-8854-c53d5a99ddbe.png)

**Comment by kapsule** [comment]
@dev-cadira ya he visto donde tienen el problema. Ya de por si el módulo de calendario (Event y Actions) tiene su tela en VTiger. Lo parieron mal y así ha seguido durante estos años. El problema, es que ese módulo tiene un error en una de las funciones que revisa el tipo de datos. Al detectar que es un multipicklist se carga el contenido de la validable. Con lo cual, cuando llega al saveRecord() el campo esta en blanco. Por ese motivo no se carga la información tras guardar :(

Ahora os paso un commit desde Cadira con la solución además de solucionar un par de bugs que he detectado en el código. Si lo probáis y no funciona ya me diréis.

**Comment by dev-cadira** [comment]
sube el cambio cuando puedas para que @jaimey lo pueda probar.
