### ISSUE TITLE
Los usuarios creados de forma previa se han "perdido"

### ISSUE THREAD

**Issue by dev-cadira** [dev-cadira/cadira#14]
Los usuarios creados de forma previa se han "perdido" están en la BD pero no los muestra el administrador de usuarios, sin embargo s{i aparecen en el contador respectivo

**Comment by kapsule** [comment]
Según se ha comentado en el foro, esto funciona sin problemas. Para poder trasladar una instancia de VTiger a Cadira se deben seguir una serie de pasos.

1. Instalar cadira por medio de git clone
2. Copiar los ficheros de configuración que tengas en la raíz de VTiger en Cadira (config.performance.inc, config.inc.php, etc...)
3. Copiar la carpeta user_priviledge de VTiger en la ruta de Cadira

Con estos cambios, la instancia de Cadira debería funcionarte sin problemas.

**Comment by dev-cadira** [comment]
@kapsule este caso lo cierre tal y como indicaste en discord.
