### ISSUE TITLE
La lista de valores picklist no se muestra de forma ordenada

### ISSUE THREAD

**Issue by kapsule** [dev-cadira/cadira#47]
No sé si sucede con versiones más actuales pero con la versión 7.1 el listado de valores de un picklist no muestra los valores ordenados.

**Comment by dev-cadira** [comment]
@kapsule ese error fue solucionado en versiones posteriores. si trabajas con versiones < 7.2 tendras ese problema. 

si necesitas solucionar el problema deberas revisar el fichero /vtiger/helpers/util.php en la función getPickListValues. dentro de esta función veras una consulta que no aplica correctamente la columna de ordenacion

espero q te sea de ayuda
