### ISSUE TITLE
I have a "Invoice" and there is a "Task"

### ISSUE THREAD

**Issue by dev-cadira** [dev-cadira/cadira#54]
Hi!. I have a "Invoice" and there is a "Task". How can I get that "activityid" from the vtiger tables using invoiceid? Or where is the relation?

![image](https://user-images.githubusercontent.com/89658833/140658860-65037510-ff06-4a23-b0c1-e6e0a6aeb021.png)

**Comment by kapsule** [comment]
Hi @dev-cadira. As indicated in telegram, this data is obtained from the following table vtiger_seactivityrel.

**Comment by dev-cadira** [comment]
thanks @kapsule!!
