### ISSUE TITLE
Alguna vez ya se les bugueo la pantalla de usuarios?

### ISSUE THREAD

**Issue by kapsule** [dev-cadira/cadira#55]
Alguna vez ya se les bugueo la pantalla de usuarios? Aquí había una larga lista pero solo se ven pocos

![image](https://user-images.githubusercontent.com/3903687/140658911-31d0f6b3-0d0b-41cb-bc13-51cc8de9c86a.png)

**Comment by dev-cadira** [comment]
Como indicó @kapsule en telegram este problema se debe a los ficheros user_priviledge. Si falta algún fichero, este listado no se muestra completo. Para solucionarlo se debe regenerar nuevamente los permisos de todos los usuarios (recalculate_role()) para que vuelvan a estar presentes. De esta forma queda solucionado el error.
