### ISSUE TITLE
Problema con lista relacionada

### ISSUE THREAD

**Issue by kapsule** [dev-cadira/cadira#75]
@dev-cadira he detectado un problema con la gestión de listas relacionadas cuando se activa el custom related list. Por algún motivo no se cargan algunos valores mostrando estos en blanco. Te ha sucedido en alguna de tus instancias?

**Comment by dev-cadira** [comment]
@kapsule contempla que la lista de campos $list_fields ahora cambia. en versiones anteriores se utiliza un sistema distinto a la versión 7. mira de especificar el nombre de la columna en vez del literal.

**Comment by kapsule** [comment]
Muchas gracias @dev-cadira. He aplicado el cambio y utilizando el literal con este cambio funciona correctamente. Esto estaría bien que se contemplará en la rama de cadira porque puede ser de gran ayuda para aquellos usuarios que quieran hacer uso del custom related list.
